version: 0.2

phases:

  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version

      - REPOSITORY_URI=407036964001.dkr.ecr.us-east-1.amazonaws.com/cicd-repo-01

      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 407036964001.dkr.ecr.us-east-1.amazonaws.com

      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo Build started
      - mvn clean install

      - echo Building Docker image...
      - docker build -t cicdtestregistry .

      - docker tag cicdtestregistry:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed
      - echo Pushing Docker image...

      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - target/*.jar